"""Match measured turn policies against the pinned reference, or validate the reference alone.

Two modes:

* reference-only (`--reference` without `--project`): validate the capture against the output
  contract in `capture.py` and print its exploitability, iteration count, stop reason and
  runout bookkeeping. It reports `project_capture: absent`, and it is a diagnostic: nothing
  it prints is acceptance of a turn solve, because no project solve was read.
* joint (`--reference` and `--project`, normally with `--review`): the turn gate. Every
  exported public history must match, and every policy row differing by more than two
  percentage points is listed. On top of the structural comparison the joint mode refuses,
  with a named failure rather than a warning:

  - a missing, empty or skipped project capture;
  - a case that did not reach its own target, or stopped for a reason other than reaching
    it, on either side;
  - any difference in the two sides' `input` tables, which carry the case id, board, ranges,
    menus, raise cap, target and starting pot;
  - a project revision that is not a commit, or is not the one `--expected-revision` names;
    the reference's pinned engine and interface revisions are checked by `validate_reference`;
  - a real-gap row with no committed entry, a committed entry for a row that is no longer
    a real gap, or no committed review at all. `review_rule.py` sorts every differing row
    into indifferent, unreached and real gap from the numbers both captures measured, so
    the first two categories are recomputed here rather than read out of a file;
  - a case whose real-gap rows cost more, reach-weighted, than the rule's budget;
  - a committed review generated under a different rule than the one in force;
  - a stale review: an entry whose recorded row values are no longer the captured ones, or
    which records no values at all and so cannot be checked against this capture.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import re
import sys
from pathlib import Path

import tomllib
from capture import (
    ENGINE_REVISION,
    MAX_OUTPUT_BYTES,
    WASM_REVISION,
    card_id,
    card_label,
    expand_range,
    read_json,
    require,
    street_wagers,
    validate_output,
)
from review_rule import classify, load_rules, same_rule, summarize

FREQUENCY_THRESHOLD = 0.02
# The stop reason each side writes when it stopped because it reached the target. Anything
# else, an iteration cap most of all, means the solve ran out of budget rather than
# converging, and the joint mode says so instead of comparing two unconverged strategies.
PROJECT_TARGET_STOP_REASON = "TargetReached"
REFERENCE_TARGET_STOP_REASON = "target"
# A review row's recorded numbers come from the same captures this run reads, so they should
# match exactly. The tolerance is here for a review regenerated by a different writer, not to
# let a re-solve through: a re-solve moves frequencies by far more than this.
REVIEW_VALUE_TOLERANCE = 1e-12
COMMIT_PATTERN = re.compile(r"^[0-9a-f]{40}$")
# Review row values the comparison recomputes, so a stale review can be caught: the path
# into the committed review row, and the field of the comparison row it must still equal.
RECORDED_ROW_VALUES = (
    (("frequency_differences",), "absolute_frequency_difference"),
    (("project_strategy",), "project_strategy"),
    (("reference_strategy",), "reference_strategy"),
    (("actions",), "actions"),
)
# Verdict fields copied onto every differing row in the report. The generated sentence
# is not among them: a report carrying 138,000 sentences is the file the rule exists to
# avoid, so only a real-gap row keeps its reasoning.
VERDICT_FIELDS = (
    "category",
    "reason",
    "reach",
    "project_switch_loss_chips",
    "reference_switch_loss_chips",
    "max_switch_loss_chips",
    "bound_chips",
    "reach_weighted_loss_chips",
)


def indexed(items, key):
    result = {}
    for item in items:
        name = key(item)
        require(name not in result, f"Repeated comparison key: {name}")
        result[name] = item
    return result


def hand_key(cards):
    return tuple(sorted(cards))


def finite_tree(value):
    if isinstance(value, float):
        require(math.isfinite(value), "Nonfinite project value")
    elif isinstance(value, dict):
        for item in value.values():
            finite_tree(item)
    elif isinstance(value, list):
        for item in value:
            finite_tree(item)


def compatible_mass(case_input):
    """Weighted count of ordered-by-player card-disjoint pairs, board cards removed."""
    board = set(case_input["board"])
    live = []
    for text in case_input["ranges"]:
        hands = {}
        for (low, high), weight in expand_range(text).items():
            cards = {
                "23456789TJQKA"[low // 4] + "cdhs"[low % 4],
                "23456789TJQKA"[high // 4] + "cdhs"[high % 4],
            }
            if not cards.intersection(board):
                hands[frozenset(cards)] = weight
        live.append(hands)
    total = 0.0
    for oop, oop_weight in live[0].items():
        for ip, ip_weight in live[1].items():
            if not oop.intersection(ip):
                total += oop_weight * ip_weight
    return total


def reference_payload(reference):
    """The shape `validate_output` needs: only `cases` is read from it."""
    return {"cases": [case["input"] for case in reference["cases"]]}


def require_raise_cap(case):
    """No exported history may hold a second raise on one street, at `max_raises: 1`.

    `capture.py` checks this node by node while the capture runs; this repeats it over the
    committed artifact and names the case and the history in the failure, so a capture file
    produced before the pruning landed cannot pass the comparison quietly. Since upstream's
    action tree holds a single chance action (`src/action_tree.rs:502-512`), every runout has
    the same betting structure, so the exported runouts cover the whole tree's shape rather
    than a sample of it.
    """
    name = case["input"]["id"]
    cap = case["input"]["max_raises"]
    for node in case["nodes"]:
        wagers = street_wagers(node["history_labels"])
        require(
            all(max(0, count - 1) <= cap for count in wagers),
            f"{name}: exported history {node['history_labels']} exceeds max_raises {cap}",
        )
        if wagers[-1] >= cap + 1:
            require(
                all(
                    action["kind"] not in {"bet", "raise", "allin"}
                    for action in node["actions"]
                ),
                f"{name}: a wager is still offered at the cap after {node['history_labels']}",
            )


def validate_reference(reference):
    require(reference.get("street") == "turn", "Reference is not a turn capture")
    provenance = reference.get("provenance", {})
    require(
        provenance.get("engine_revision") == ENGINE_REVISION, "Wrong reference engine"
    )
    require(
        provenance.get("wasm_postflop_revision") == WASM_REVISION,
        "Wrong reference interface",
    )
    interface = reference.get("interface", {})
    require(
        interface.get("strategy_layout") == "action_major", "Wrong reference row layout"
    )
    require(
        interface.get("rake_rate") == 0 and interface.get("rake_cap") == 0,
        "Reference rake differs",
    )
    validate_output(
        reference,
        reference_payload(reference),
        reference.get("execution_stop_policy", "target_or_cap")
        == "fixed_iteration_budget",
        reference.get("presentation_mode", "upstream_display") == "raw_f32",
    )
    for case in reference["cases"]:
        require_raise_cap(case)


def swap_suits(label, first, second):
    if label[1] == first:
        return label[0] + second
    if label[1] == second:
        return label[0] + first
    return label


def ranges_are_suit_symmetric(case_input, first, second):
    """Whether swapping two suits leaves both input ranges unchanged, weights included."""
    for text in case_input["ranges"]:
        weights = expand_range(text)
        swapped = {}
        for (low, high), weight in weights.items():
            pair = tuple(
                sorted(
                    card_id(swap_suits(card_label(card), first, second))
                    for card in (low, high)
                )
            )
            swapped[pair] = weight
        if swapped != weights:
            return False
    return True


def isomorphic_runout_pairs(case):
    """Exported runouts the reference should have merged, and how far their rows agree.

    The engine deals a merged card by replaying its representative and swapping the suits
    back, so two exported runouts of the same rank whose suits are interchangeable on this
    board must produce policies that map onto each other exactly under that swap. It is the
    one property of the reference's isomorphism that our own runout handling has to respect,
    so it is checked here rather than taken on trust.
    """
    board = case["input"]["board"]
    exported = case["input"]["export_runouts"]
    private = [
        [tuple(sorted(entry["cards"])) for entry in case["private_cards"][player]]
        for player in (0, 1)
    ]
    index = [
        {hand: position for position, hand in enumerate(private[player])}
        for player in (0, 1)
    ]
    nodes = {tuple(node["history_labels"]): node for node in case["nodes"]}
    reports = []
    for first in exported:
        for second in exported:
            if first >= second or first[0] != second[0]:
                continue
            suits = (first[1], second[1])
            if sorted(swap_suits(card, *suits) for card in board) != sorted(board):
                continue
            if not ranges_are_suit_symmetric(case["input"], *suits):
                continue
            compared = 0
            worst = 0.0
            for history, node in nodes.items():
                if node["kind"] != "decision" or node["runout"] != first:
                    continue
                twin = nodes.get(
                    tuple(
                        f"chance:{second}" if step == f"chance:{first}" else step
                        for step in history
                    )
                )
                require(twin is not None, f"{first} has no {second} twin history")
                require(
                    [a["label"] for a in node["actions"]]
                    == [a["label"] for a in twin["actions"]],
                    f"Isomorphic runouts {first} and {second} offer different actions",
                )
                player = node["player"]
                count = len(private[player])
                for hand in private[player]:
                    if first in hand or second in hand:
                        continue
                    mine = index[player][hand]
                    theirs = index[player][
                        tuple(sorted(swap_suits(card, *suits) for card in hand))
                    ]
                    for action in range(len(node["actions"])):
                        worst = max(
                            worst,
                            abs(
                                node["strategy"][action * count + mine]
                                - twin["strategy"][action * count + theirs]
                            ),
                        )
                        compared += 1
            require(
                compared > 0,
                f"Isomorphic runouts {first} and {second} share no comparable rows",
            )
            require(
                worst == 0.0,
                f"Isomorphic runouts {first} and {second} differ by {worst} after the "
                "suit swap; the reference did not merge them as expected",
            )
            reports.append(
                {
                    "runouts": [first, second],
                    "swapped_suits": list(suits),
                    "compared_cells": compared,
                    "max_absolute_difference": worst,
                }
            )
    return reports


def summarize_reference(reference):
    """Reference-only report: what the capture measured, without any project comparison."""
    validate_reference(reference)
    cases = []
    for case in reference["cases"]:
        chance = [node for node in case["nodes"] if node["kind"] == "chance"]
        require(chance, "A turn capture must expose at least one chance node")
        possible = {len(node["possible_cards"]) for node in chance}
        merged = {node["isomorphic_merged_cards"] for node in chance}
        cases.append(
            {
                "id": case["input"]["id"],
                "board": case["input"]["board"],
                "max_raises": case["input"]["max_raises"],
                "removed_lines": case["removed_lines"],
                "max_street_wagers": max(
                    max(street_wagers(node["history_labels"])) for node in case["nodes"]
                ),
                "iterations": case["iterations"],
                "stop_reason": case["stop_reason"],
                "target_pct_of_pot": case["input"]["target_pct_of_pot"],
                "exploitability_chips": case["exploitability_chips"],
                "exploitability_pct_of_pot": case["exploitability_pct_of_pot"],
                "reached_target": case["exploitability_pct_of_pot"]
                <= case["input"]["target_pct_of_pot"],
                "root_centered_expected_values": case["root_centered_expected_values"],
                "exported_nodes": len(case["nodes"]),
                "chance_nodes": len(chance),
                "dealable_runouts": sorted(possible),
                "isomorphic_merged_runouts": sorted(merged),
                "exported_runouts": case["input"]["export_runouts"],
                "isomorphic_runout_pairs": isomorphic_runout_pairs(case),
                "private_hand_counts": [
                    len(entries) for entries in case["private_cards"]
                ],
                "reference_memory_estimate_bytes": case[
                    "reference_memory_estimate_bytes"
                ],
                "elapsed_seconds": case["elapsed_seconds"],
            }
        )
    return {
        "schema_version": 1,
        "mode": "reference_only",
        "project_capture": "absent",
        "structural_and_convergence_checks": "passed",
        "note": (
            "No project capture exists yet, so no frequency comparison was made. "
            "The reference solved every runout; only the runouts named in export_runouts "
            "were exported."
        ),
        "cases": cases,
    }


WAGER_LABEL = re.compile(r"^(bet|raise|allin):(\d+)$")


def street_relative_labels(node):
    """One project node's actions in the reference's per-street wager convention.

    Our tree names a wager by the total the actor will have committed since the root, so at
    a river history where the actor already put 4 in on the turn, `Action::Bet(10)` is the
    reference's `bet:6`. The two conventions coincide on a river-rooted tree, which is why
    phase 3 never had to say which one it used.

    Restating here rather than accepting either name makes the difference a checked
    equivalence: the restated wager is the reference's only if the two trees agree about the
    chips, and `compare` still refuses the node if they do not.
    """
    if node["kind"] != "decision":
        return list(node["actions"])
    standing = node["contributions"][node["player"]]
    labels = []
    for label in node["actions"]:
        match = WAGER_LABEL.match(label)
        if match is None:
            require(
                label in {"fold", "check", "call"},
                f"Unknown project action {label}",
            )
            labels.append(label)
            continue
        amount = int(match[2]) - standing
        require(
            amount > 0,
            f"Project wager {label} does not exceed the actor's committed {standing}",
        )
        labels.append(f"{match[1]}:{amount}")
    return labels


def restate_project_labels(project):
    """Restate every project case's labels in the reference's per-street convention.

    In place, and marked done on the case, so the report, `oracle.py` and `review_combos.py`
    all read one set of labels and a second call changes nothing.
    """
    restated = 0
    for case in project["cases"]:
        if case.get("label_convention") == "per_street":
            continue
        nodes = {tuple(node["history_labels"]): node for node in case["nodes"]}
        require(len(nodes) == len(case["nodes"]), "Repeated project history")
        renamed = {
            history: street_relative_labels(node) for history, node in nodes.items()
        }
        # Histories first: they are read through the original action labels.
        for node in case["nodes"]:
            history = tuple(node["history_labels"])
            labels = []
            for depth, step in enumerate(history):
                parent = nodes.get(history[:depth])
                require(
                    parent is not None,
                    f"Project history {list(history)} has no node at {list(history[:depth])}",
                )
                if parent["kind"] == "decision":
                    labels.append(
                        renamed[history[:depth]][parent["actions"].index(step)]
                    )
                else:
                    labels.append(step)
            node["history_labels"] = labels
        for history, node in nodes.items():
            restated += sum(
                old != new
                for old, new in zip(node["actions"], renamed[history], strict=True)
            )
            node["actions"] = renamed[history]
        case["label_convention"] = "per_street"
    return restated


def called_all_in_runouts(case):
    """Project chance nodes that only run the board out, mapped to the histories they own.

    After a called all-in on the turn our tree still deals the river, so the line holds one
    chance node and one showdown terminal per exported card and not a single decision. The
    reference ends the same line at a turn showdown whose value already spans every runout.
    Both describe the same game and neither holds a policy row, so the comparison checks the
    two against each other as an equivalence and compares the histories both sides export.

    Only a chance node whose every exported child is a childless showdown terminal at the
    same contributions qualifies. An ordinary turn deal opens river betting with a decision,
    so it is never mistaken for one of these.
    """
    nodes = {tuple(node["history_labels"]): node for node in case["nodes"]}
    children = {}
    for history in nodes:
        if history:
            children.setdefault(history[:-1], []).append(history)
    runouts = {}
    for history, node in nodes.items():
        if node["kind"] != "chance" or node["street"] != "turn":
            continue
        owned = children.get(history, [])
        if owned and all(
            nodes[child]["kind"] == "terminal"
            and nodes[child]["terminal"] == "showdown"
            and nodes[child]["contributions"] == node["contributions"]
            and not children.get(child)
            for child in owned
        ):
            runouts[history] = sorted(owned)
    return runouts


def compare(project, reference):
    finite_tree(project)
    require(project.get("schema_version") == 1, "Unknown project schema")
    require(project.get("street") == "turn", "Project capture is not a turn capture")
    validate_reference(reference)
    restated_labels = restate_project_labels(project)
    ours = indexed(project["cases"], lambda c: c["input"]["id"])
    theirs = indexed(reference["cases"], lambda c: c["input"]["id"])
    require(ours.keys() == theirs.keys(), "Case set differs")
    reports = []
    for name, own in ours.items():
        ref = theirs[name]
        require(own["input"] == ref["input"], f"{name}: input differs")
        pot = own["input"]["starting_pot"]
        br = own["best_response_values"]
        require(
            len(br) == 2
            and abs(50 * max(0, sum(br)) / pot - own["exploitability_pct_of_pot"])
            <= 1e-10,
            "Project best-response metric units differ",
        )
        policy = project.get("execution_stop_policy", "target_or_cap")
        if policy == "fixed_iteration_budget":
            require(
                own["stop_reason"] == policy
                and own["iterations"] == own["input"]["max_iterations"],
                "Project fixed budget is incomplete",
            )
        else:
            require(policy == "target_or_cap", "Unknown project stop policy")
            reason = (
                "TargetReached"
                if own["exploitability_pct_of_pot"] <= own["input"]["target_pct_of_pot"]
                else "IterationCap"
            )
            require(own["stop_reason"] == reason, "Project target/cap reason differs")
            require(
                reason != "IterationCap"
                or own["iterations"] == own["input"]["max_iterations"],
                "Project cap is incomplete",
            )
        expected_mass = compatible_mass(own["input"])
        require(
            abs(own["compatible_weight"] - expected_mass)
            <= 1e-6 * max(1.0, expected_mass),
            "Root compatible mass differs",
        )
        for result in (own, ref):
            require(
                -0.001 <= result["exploitability_pct_of_pot"] < 0.5,
                f"{name}: convergence gate failed",
            )
        # The board-run-out lines below a called all-in are the project's alone. They hold no
        # policy row, and the reference's turn showdown at the same history is the same game;
        # the loop below checks that equivalence node by node.
        run_outs = called_all_in_runouts(own)
        owned = {history for children in run_outs.values() for history in children}
        pn = indexed(
            (n for n in own["nodes"] if tuple(n["history_labels"]) not in owned),
            lambda n: tuple(n["history_labels"]),
        )
        rn = indexed(ref["nodes"], lambda n: tuple(n["history_labels"]))
        require(pn.keys() == rn.keys(), f"{name}: public history set differs")
        all_in_run_outs = []
        differences = []
        checked_rows = 0
        max_frequency_difference = 0.0
        max_available_action_ev_difference = 0.0
        committed_fold_origin_cells = 0
        runout_reports = []
        for history, node in pn.items():
            other = rn[history]
            if history in run_outs:
                require(
                    other["kind"] == "terminal"
                    and other["terminal"] == "showdown"
                    and other["street"] == "turn",
                    f"{name} {history}: the project runs the board out here with no "
                    "decision left, but the reference does not end the hand",
                )
                require(
                    node["contributions"] == other["contributions"],
                    f"{name} {history}: chip contributions differ",
                )
                all_in_run_outs.append(
                    {
                        "history": list(history),
                        "contributions": node["contributions"],
                        "project_dealable_runouts": len(node["possible_cards"]),
                        "project_exported_showdowns": len(run_outs[history]),
                        "reference_node": "turn showdown terminal",
                    }
                )
                continue
            require(
                node["kind"] == other["kind"], f"{name} {history}: node kind differs"
            )
            require(
                node["street"] == other["street"]
                and (node.get("runout") or None) == (other.get("runout") or None),
                f"{name} {history}: street or runout differs",
            )
            require(
                node["contributions"] == other["contributions"],
                f"{name} {history}: chip contributions differ",
            )
            if node["kind"] == "chance":
                require(
                    sorted(node["possible_cards"]) == sorted(other["possible_cards"]),
                    f"{name} {history}: dealable runout set differs",
                )
                runout_reports.append(
                    {
                        "history": list(history),
                        "dealable_runouts": len(other["possible_cards"]),
                        "reference_representative_actions": other[
                            "representative_action_count"
                        ],
                        "reference_isomorphic_merged": other["isomorphic_merged_cards"],
                        "project_isomorphic_merged": node.get(
                            "isomorphic_merged_cards", 0
                        ),
                    }
                )
                continue
            require(
                node["actions"] == [a["label"] for a in other["actions"]],
                f"{name} {history}: actions differ",
            )
            if node["kind"] == "terminal":
                require(
                    node["terminal"] == other["terminal"], "Terminal reason differs"
                )
                if node["terminal"] == "fold":
                    require(
                        node["fold_winner"] == other["fold_winner"],
                        "Fold winner differs",
                    )
                continue
            player = node["player"]
            require(player == other["player"], "Acting player differs")
            private = ref["private_cards"][player]
            count = len(private)
            indices = indexed(
                enumerate(private), lambda pair: hand_key(pair[1]["cards"])
            )
            hands = indexed(node["hands"], lambda h: hand_key(h["cards"]))
            runout = {node["runout"]} if node.get("runout") else set()
            dead = set(own["input"]["board"]) | runout
            live = {key for key in indices if not set(key).intersection(dead)}
            require(
                hands.keys() == live, f"{name} {history}: physical combo set differs"
            )
            for key, hand in hands.items():
                checked_rows += 1
                index = indices[key][0]
                own_policy = hand["strategy"]
                n = len(node["actions"])
                require(
                    len(own_policy) == n
                    and all(0 <= p <= 1 for p in own_policy)
                    and abs(sum(own_policy) - 1) < 1e-10,
                    "Invalid project policy row",
                )
                ref_policy = [other["strategy"][a * count + index] for a in range(n)]
                delta = [
                    abs(a - b) for a, b in zip(own_policy, ref_policy, strict=True)
                ]
                max_frequency_difference = max(max_frequency_difference, *delta)
                ref_available = other["ev_available"][index]
                available = hand["ev_available"] and ref_available
                ev = hand["action_expected_values"]
                require(
                    len(ev) == (n if hand["ev_available"] else 0),
                    "Project EV availability differs",
                )
                ref_ev = []
                if ref_available:
                    origin = pot / 2 + other["reported_contributions"][player]
                    ref_ev = [
                        other["action_expected_values"][a * count + index] - origin
                        for a in range(n)
                    ]
                    if "fold" in node["actions"]:
                        fold = node["actions"].index("fold")
                        expected = -pot / 2 - node["contributions"][player]
                        if hand["ev_available"]:
                            require(
                                abs(ev[fold] - expected) <= 1e-9,
                                "Project fold EV origin differs",
                            )
                        require(
                            abs(ref_ev[fold] - expected) <= 1e-6,
                            "Reference fold EV origin differs",
                        )
                        if hand["ev_available"] and node["contributions"][player] > 0:
                            committed_fold_origin_cells += 1
                if available:
                    max_available_action_ev_difference = max(
                        max_available_action_ev_difference,
                        *(abs(a - b) for a, b in zip(ev, ref_ev, strict=True)),
                    )
                changed = [a for a, d in enumerate(delta) if d > FREQUENCY_THRESHOLD]
                if changed:
                    differences.append(
                        {
                            "history": list(history),
                            "street": node["street"],
                            "runout": node.get("runout") or None,
                            "player": player,
                            "cards": list(key),
                            "actions": node["actions"],
                            "changed_action_indices": changed,
                            "project_strategy": own_policy,
                            "reference_strategy": ref_policy,
                            "absolute_frequency_difference": delta,
                            "project_action_ev": ev if hand["ev_available"] else None,
                            "reference_action_ev": ref_ev if ref_available else None,
                            "project_action_gap": (
                                [max(ev) - v for v in ev] if ev else None
                            ),
                            "reference_action_gap": (
                                [max(ref_ev) - v for v in ref_ev] if ref_ev else None
                            ),
                            "project_own_reach": hand["own_reach"],
                            "project_opponent_mass": hand["opponent_mass"],
                            "reference_display_own_reach": other["reach_weights"][
                                index
                            ],
                            "both_evs_available": available,
                            "reference_ev_available": ref_available,
                            "project_ev_available": hand["ev_available"],
                            "review_status": "requires_per_combo_review",
                        }
                    )
        root_delta = [
            abs(a - b)
            for a, b in zip(
                own["root_centered_expected_values"],
                ref["root_centered_expected_values"],
                strict=True,
            )
        ]
        reports.append(
            {
                "id": name,
                "max_raises": own["input"]["max_raises"],
                "reference_removed_lines": ref["removed_lines"],
                "matched_nodes": len(pn),
                "matched_policy_rows": checked_rows,
                "committed_fold_origin_cells": committed_fold_origin_cells,
                "project_pct_of_pot": own["exploitability_pct_of_pot"],
                "reference_pct_of_pot": ref["exploitability_pct_of_pot"],
                "project_iterations": own["iterations"],
                "reference_iterations": ref["iterations"],
                "root_ev_absolute_difference": root_delta,
                "max_frequency_difference": max_frequency_difference,
                "max_available_action_ev_difference": max_available_action_ev_difference,
                "frequency_rows_requiring_review": len(differences),
                "called_all_in_run_outs": all_in_run_outs,
                "chance_nodes": runout_reports,
                "isomorphic_runout_pairs": isomorphic_runout_pairs(ref),
                "differences": differences,
            }
        )
    require(
        sum(case["committed_fold_origin_cells"] for case in reports) > 0,
        "No raised-history fold established the contribution EV offset",
    )
    return {
        "schema_version": 1,
        "mode": "project_versus_reference",
        "structural_and_convergence_checks": "passed",
        "tree_reconciliation": {
            "project_wager_labels_restated": restated_labels,
            "note": (
                "The project names a wager by the actor's total commitment since the root "
                "and the reference names the chips going in on this street; the restated "
                "labels have to match, so the chips still have to agree. Where the project "
                "deals the river after a called all-in the reference ends the hand at a turn "
                "showdown; those lines hold no policy row and are reported per case under "
                "called_all_in_run_outs."
            ),
        },
        "frequency_review": (
            "required"
            if any(r["differences"] for r in reports)
            else "within_two_percentage_points"
        ),
        "ev_scope": (
            "Action EVs follow each respective policy; root residuals are not per-hand error "
            "bounds. Only the runouts named in export_runouts are compared; both sides solved "
            "every runout."
        ),
        "cases": reports,
    }


def row_key(case_id, history, cards):
    return (case_id, tuple(history), tuple(sorted(cards)))


def row_context(review):
    """What a committed review row copies out of a comparison row.

    Enough to find the row again, and enough for `stale_reviews` to prove the record
    still describes these captures rather than an older pair of solves.
    """
    # Copied, not aliased: the record is a statement about what the comparison said,
    # and an entry that moves when the comparison does could never be found stale.
    return {
        "history": list(review["history"]),
        "street": review["street"],
        "runout": review["runout"],
        "player": review["player"],
        "cards": list(review["cards"]),
        "actions": list(review["actions"]),
        "frequency_differences": list(review["absolute_frequency_difference"]),
        "project_strategy": list(review["project_strategy"]),
        "reference_strategy": list(review["reference_strategy"]),
    }


def review_rows(review):
    """Map (case id, history, cards) to the committed review row itself."""
    require(
        type(review) is dict and type(review.get("cases")) is list,
        "Invalid review file",
    )
    rows = {}
    for case in review["cases"]:
        for row in case.get("rows", []):
            rows[row_key(case["id"], row["history"], row["cards"])] = row
    return rows


def dig(row, path):
    """Follow a field path into a review row, or `None` if it is not recorded."""
    value = row
    for step in path:
        if type(value) is not dict:
            return None
        value = value.get(step)
    return value


def same_values(recorded, measured):
    """Whether a recorded review value still equals what the captures now say."""
    if type(recorded) is not list or type(measured) is not list:
        return recorded == measured
    if len(recorded) != len(measured):
        return False
    for old, new in zip(recorded, measured, strict=True):
        if type(old) in {int, float} and type(new) in {int, float}:
            if (
                not math.isfinite(old)
                or not math.isfinite(new)
                or abs(old - new) > REVIEW_VALUE_TOLERANCE
            ):
                return False
        elif old != new:
            return False
    return True


def stale_reviews(report, review):
    """Committed review rows that no longer describe the captures being compared.

    A recorded row is a statement about numbers somebody read. Re-solve either side and
    those numbers move, so the record then describes a row that no longer exists. Every
    covered row therefore has to record at least one of the values the comparison
    recomputes, and each recorded value has to still match. A row that records nothing is
    not evidence of anything and is reported as unverifiable, not accepted.

    Rows with no committed entry at all are `unrecorded_rows`' business, not this one's.
    """
    if review is None:
        return []
    rows = review_rows(review)
    stale = []
    for case in report["cases"]:
        for row in case["differences"]:
            entry = rows.get(row_key(case["id"], row["history"], row["cards"]))
            if entry is None:
                continue
            recorded = 0
            for path, field in RECORDED_ROW_VALUES:
                value = dig(entry, path)
                if value is None:
                    continue
                recorded += 1
                if not same_values(value, row[field]):
                    stale.append(
                        {
                            "id": case["id"],
                            "history": row["history"],
                            "cards": row["cards"],
                            "field": ".".join(path),
                            "reason": "the reviewed value is not the captured one",
                            "reviewed": value,
                            "captured": row[field],
                        }
                    )
            if recorded == 0:
                stale.append(
                    {
                        "id": case["id"],
                        "history": row["history"],
                        "cards": row["cards"],
                        "field": None,
                        "reason": (
                            "the review records no row values, so it cannot be checked "
                            "against this capture"
                        ),
                    }
                )
    return stale


def convergence_failures(project, reference):
    """Cases that did not converge, or that stopped for some reason other than the target.

    Both sides are held to the case's own target, not to the looser structural bound
    `compare` uses. Two unconverged strategies can agree with each other and still be wrong,
    so a comparison over them is not evidence about either.
    """
    ours = indexed(project["cases"], lambda c: c["input"]["id"])
    theirs = indexed(reference["cases"], lambda c: c["input"]["id"])
    failures = []
    for name, own in ours.items():
        ref = theirs[name]
        target = own["input"]["target_pct_of_pot"]
        for side, case, expected in (
            ("project", own, PROJECT_TARGET_STOP_REASON),
            ("reference", ref, REFERENCE_TARGET_STOP_REASON),
        ):
            measured = case["exploitability_pct_of_pot"]
            reached = measured <= target
            entry = {
                "id": name,
                "side": side,
                "target_pct_of_pot": target,
                "exploitability_pct_of_pot": measured,
                "stop_reason": case["stop_reason"],
                "iterations": case["iterations"],
            }
            if not reached:
                failures.append(entry | {"check": "reached_target"})
            elif case["stop_reason"] != expected:
                failures.append(
                    entry | {"check": "stop_reason", "expected_stop_reason": expected},
                )
            claimed = case.get("reached_target")
            if type(claimed) is bool and claimed != reached:
                failures.append(
                    entry
                    | {
                        "check": "reported_reached_target",
                        "reported_reached_target": claimed,
                    }
                )
    return failures


def revision_failures(project, expected_revision):
    """The project capture must name the commit it measured, and it must be the right one."""
    failures = []
    revision = project.get("project_revision")
    if type(revision) is not str or not COMMIT_PATTERN.match(revision):
        return [
            {
                "check": "project_revision",
                "project_revision": revision,
                "reason": "the capture does not name a 40-character commit",
            }
        ]
    if expected_revision is not None and revision != expected_revision:
        failures.append(
            {
                "check": "project_revision",
                "project_revision": revision,
                "expected_revision": expected_revision,
                "reason": "the capture measured a different commit",
            }
        )
    return failures


def classify_rows(report, project, rules):
    """Sort every differing row by rule, in place, and summarize each case.

    This is the review, recomputed here rather than read from the committed file. What
    the file is for is the rows the rule refuses to excuse: those have to have been seen
    by a person, so the gate checks the recomputed list against the recorded one.
    """
    weights = indexed(project["cases"], lambda case: case["input"]["id"])
    summaries = []
    for case in report["cases"]:
        own = weights[case["id"]]
        pot = own["input"]["starting_pot"]
        verdicts = []
        for row in case["differences"]:
            verdict = classify(row, pot, own["compatible_weight"], rules)
            verdicts.append(verdict)
            row["review_status"] = "reviewed_by_rule"
            row.update({name: verdict[name] for name in VERDICT_FIELDS})
            if verdict["category"] == "real_gap":
                row["review_reasoning"] = verdict["review_reasoning"]
        summaries.append(summarize(case["id"], pot, verdicts, rules))
    return summaries


def real_gap_keys(report):
    """Every row the rule calls a real gap, by (case id, history, cards)."""
    return {
        row_key(case["id"], row["history"], row["cards"])
        for case in report["cases"]
        for row in case["differences"]
        if row.get("category") == "real_gap"
    }


def unrecorded_rows(report, review):
    """Real-gap rows with no committed entry, and committed entries that are not one.

    A row the rule cannot excuse is a row a person has to have looked at, so it must be
    in the file. The other direction matters too: an entry for a row the current
    captures no longer call a real gap describes something that is not there any more.
    """
    recorded = set(review_rows(review)) if review is not None else set()
    real = real_gap_keys(report)
    missing = [
        {"id": name, "history": list(history), "cards": list(cards)}
        for name, history, cards in sorted(real - recorded)
    ]
    extra = [
        {
            "id": name,
            "history": list(history),
            "cards": list(cards),
            "reason": "the committed record lists a row the rule no longer calls a real gap",
        }
        for name, history, cards in sorted(recorded - real)
    ]
    return missing, extra


def budget_failures(summaries, rules):
    """Cases whose real-gap rows cost more than the rule's budget allows."""
    return [
        {
            "check": "real_gap_budget",
            "id": summary["id"],
            "real_gap_reach_weighted_loss_chips": summary[
                "real_gap_reach_weighted_loss_chips"
            ],
            "real_gap_pot_fraction": summary["real_gap_pot_fraction"],
            "budget_pot_fraction": rules["real_gap_budget_pot_fraction"],
            "real_gap_rows": summary["counts"]["real_gap"],
        }
        for summary in summaries
        if not summary["within_budget"]
    ]


def rule_failures(review, rules):
    """A committed record generated under different thresholds cannot be read now.

    The record stores the rule and the hash of the file it came from. Judge old rows by
    new numbers and the counts in the file stop describing anything.
    """
    if review is None:
        return [
            {
                "check": "review_supplied",
                "reason": (
                    "no committed per-combo review, so no real-gap row has been seen by "
                    "anyone"
                ),
            }
        ]
    if review.get("schema_version") != 2:
        return [
            {
                "check": "review_schema",
                "review_schema_version": review.get("schema_version"),
                "reason": "the review is not a version 2 rule-based record",
            }
        ]
    if not same_rule(review.get("rule"), rules):
        return [
            {
                "check": "review_rule",
                "recorded_rule": review.get("rule"),
                "current_rule": rules,
                "reason": "the record was generated under a different rule",
            }
        ]
    return []


def joint_report(project, reference, review, expected_revision, rules):
    """The whole joint gate over parsed captures: the comparison and every refusal.

    `accepted` is the gate's answer. It is false whenever any rule refused, and the reason
    is in `gate_failures`, `rows_missing_review` or `stale_review_rows`; the caller turns
    that into an exit status. Keeping it here rather than in `main` is what lets
    `test_compare.py` prove each refusal without writing a TOML file.
    """
    result = compare(project, reference)
    summaries = classify_rows(result, project, rules)
    missing, extra = unrecorded_rows(result, review)
    stale = stale_reviews(result, review) + extra
    failures = (
        convergence_failures(project, reference)
        + revision_failures(project, expected_revision)
        + rule_failures(review, rules)
        + budget_failures(summaries, rules)
    )
    result["review"] = {"rule": rules, "cases": summaries}
    result["rows_missing_review"] = missing
    result["stale_review_rows"] = stale
    result["gate_failures"] = failures
    result["gate"] = {
        "project_revision": project.get("project_revision"),
        "expected_revision": expected_revision or "not supplied",
        "revision_checked_against_workflow": expected_revision is not None,
        "reference_engine_revision": ENGINE_REVISION,
        "reference_wasm_postflop_revision": WASM_REVISION,
        "review_supplied": review is not None,
    }
    result["accepted"] = not (missing or stale or failures)
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reference", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--project", type=Path)
    parser.add_argument(
        "--review",
        type=Path,
        help="Committed per-combo-review.json; every real-gap row must appear in it",
    )
    parser.add_argument(
        "--rules",
        type=Path,
        help="Review thresholds; defaults to review_rules.json beside this script",
    )
    parser.add_argument(
        "--expected-revision",
        help="Commit the project capture must name, normally the workflow's own SHA",
    )
    args = parser.parse_args()
    reference = read_json(args.reference, MAX_OUTPUT_BYTES)
    hashes = {"reference": hashlib.sha256(args.reference.read_bytes()).hexdigest()}
    failures = []
    if args.project is None:
        require(
            args.review is None,
            "A review file is only meaningful with a project capture",
        )
        require(
            args.expected_revision is None,
            "A project revision is only meaningful with a project capture",
        )
        result = summarize_reference(reference)
        missing = []
        stale = []
    else:
        # A skipped `turn-solve` leaves no capture behind. Saying so here, by name, is the
        # difference between a red gate and a green job that compared nothing.
        require(
            args.project.is_file(),
            f"The project capture {args.project} is missing or was never written; a "
            "reference-only summary is never acceptance of a turn solve",
        )
        size = args.project.stat().st_size
        require(size > 0, f"The project capture {args.project} is empty")
        require(size <= MAX_OUTPUT_BYTES, "Project file exceeds 64 MiB")
        project = tomllib.loads(args.project.read_text(encoding="utf-8"))
        hashes["project"] = hashlib.sha256(args.project.read_bytes()).hexdigest()
        review = None
        if args.review is not None:
            review = read_json(args.review, MAX_OUTPUT_BYTES)
            hashes["review"] = hashlib.sha256(args.review.read_bytes()).hexdigest()
        rules = load_rules(args.rules)
        result = joint_report(
            project, reference, review, args.expected_revision, rules
        )
        missing = result["rows_missing_review"]
        stale = result["stale_review_rows"]
        failures = result["gate_failures"]
    result["input_sha256"] = hashes
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.open("x", encoding="utf-8") as stream:
        json.dump(result, stream, allow_nan=False, indent=2)
        stream.write("\n")
    bulky = {
        "cases",
        "input_sha256",
        "rows_missing_review",
        "stale_review_rows",
        "review",
    }
    summary = {key: value for key, value in result.items() if key not in bulky} | {
        "rows_missing_review": len(missing),
        "stale_review_rows": len(stale),
        "cases": [
            {k: v for k, v in case.items() if k != "differences"}
            for case in result["cases"]
        ],
    }
    if "review" in result:
        summary["review"] = {
            "rule": result["review"]["rule"],
            "cases": [
                {k: v for k, v in case.items() if k != "rows"}
                for case in result["review"]["cases"]
            ],
        }
    print(json.dumps(summary, indent=2))
    refused = False
    if failures:
        for failure in failures:
            print(f"Turn gate failure: {json.dumps(failure)}", file=sys.stderr)
        refused = True
    if missing:
        for entry in missing[:20]:
            print(f"Unrecorded real gap: {json.dumps(entry)}", file=sys.stderr)
        print(
            f"{len(missing)} rows differ by more than "
            f"{100 * FREQUENCY_THRESHOLD:.0f} percentage points, cost more than the rule "
            "allows, and are in no committed per-combo review",
            file=sys.stderr,
        )
        refused = True
    if stale:
        for entry in stale[:20]:
            print(f"Stale review row: {json.dumps(entry)}", file=sys.stderr)
        print(
            f"{len(stale)} committed review rows no longer describe these captures",
            file=sys.stderr,
        )
        refused = True
    if refused:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
