"""Build the committed per-combo review from the two turn captures, by rule.

`compare.py --review` reads the result. The reasoning for every differing row is
generated by `review_rule.py` from the numbers the two captures measured, so this
script writes down only what the rule cannot excuse: the rule itself, the counts, and
every C row with its reach-weighted loss. The A and B rows are regenerated at compare
time from the same rule and the same captures, which is why they are not stored: a
sentence about a row is only worth keeping if the row is one somebody has to look at.

    python tests/reference/turn/review_combos.py \\
      target/turn-project/cases.toml \\
      target/turn-reference/cases.json \\
      tests/reference/turn/per-combo-review.json

The river's review is a different document and stays as it is: it compares a refined
solve four orders of magnitude tighter than this gate's target, where a two-point
difference in a frequency really is one row a person should read.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import tomllib
from capture import MAX_OUTPUT_BYTES, read_json, require
from compare import compare, row_context
from review_rule import classify, load_rules, summarize

SCHEMA_VERSION = 2


def review(project, reference, rules):
    """The committed record: the rule, the counts, and the real-gap rows."""
    cases = []
    weights = {case["input"]["id"]: case for case in project["cases"]}
    for case in compare(project, reference)["cases"]:
        own = weights[case["id"]]
        pot = own["input"]["starting_pot"]
        verdicts = []
        rows = []
        for row in case["differences"]:
            verdict = classify(row, pot, own["compatible_weight"], rules)
            verdicts.append(verdict)
            if verdict["category"] == "real_gap":
                rows.append(row_context(row) | verdict)
        summary = summarize(case["id"], pot, verdicts, rules)
        cases.append(summary | {"rows": rows})
    return {
        "schema_version": SCHEMA_VERSION,
        "street": "turn",
        "rule": rules,
        "scope": (
            "Every policy row differing by more than two percentage points on any action, "
            "over the exported runouts, sorted into indifferent, unreached and real gap by "
            "review_rule.py. Only the real-gap rows are stored; the other two categories "
            "are regenerated by compare.py --review from these same captures. Reach is the "
            "root probability of the information set and losses are chips, so a row's "
            "reach-weighted loss is comparable across rows and their sum is the gate's "
            "number."
        ),
        "acceptance": "compare.py --review recomputes every category and the budget",
        "cases": cases,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("project", type=Path)
    parser.add_argument("reference", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument(
        "--rules",
        type=Path,
        help="Thresholds to generate under; defaults to review_rules.json beside this file",
    )
    args = parser.parse_args()
    rules = load_rules(args.rules)
    hashes = {}
    for name in ("project", "reference"):
        path = getattr(args, name)
        require(path.stat().st_size <= MAX_OUTPUT_BYTES, f"Oversized {name} capture")
        hashes[name] = hashlib.sha256(path.read_bytes()).hexdigest()
    project = tomllib.loads(args.project.read_text(encoding="utf-8"))
    reference = read_json(args.reference, MAX_OUTPUT_BYTES)
    report = review(project, reference, rules)
    report["generated_from"] = hashes | {
        "project_revision": project.get("project_revision"),
        "project_os": project.get("os"),
    }
    with args.output.open("w", encoding="utf-8") as stream:
        json.dump(report, stream, indent=2, allow_nan=False)
        stream.write("\n")
    print(
        json.dumps(
            [{k: v for k, v in case.items() if k != "rows"} for case in report["cases"]],
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
