"""Export Rust-test TOML only from completed, inspected reference captures."""

import hashlib
import importlib.metadata
import json
import platform
from pathlib import Path

import pyspiel

from dcfr_reference import source_sha256 as dcfr_source_sha256

HERE = Path(__file__).parent
BUDGETS = {
    "kuhn": {"cfr": (10000, 1e-3), "cfr_plus": (200000, 1e-5), "dcfr": (200000, 1e-5)},
    "leduc": {"cfr": (10000, 0.005), "cfr_plus": (1000, 1e-3), "dcfr": (2000, 1e-4)},
}


def main():
    """Refuse missing budgets, incomplete runs, or residuals outside their gate."""
    sources = {}
    for game, variants in BUDGETS.items():
        lines = ["# Generated by tests/reference/openspiel/export_fixtures.py."]
        for variant, (budget, target) in variants.items():
            path = HERE / f"{game}_{variant}.json"
            data = json.loads(path.read_text(encoding="utf-8"))
            if not data["complete"]:
                raise ValueError(f"Incomplete capture: {path.name}")
            measured = next(p for p in data["checkpoints"] if p["iteration"] == budget)
            if target is not None and measured["nash_conv"] >= target:
                raise ValueError(
                    f"Captured {game}/{variant} misses its fixed accuracy gate"
                )
            sources[path.name] = {
                "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
                "command": f"python tests/reference/openspiel/capture.py --game {game} --variant {variant} --max-iterations {data['checkpoints'][-1]['iteration']}",
                "game_parameters": data["game_parameters"],
                "captured_utc": data["captured_utc"],
                "executed_upstream_cfr_python_sha256": data["cfr_python_sha256"],
            }
            if "executed_local_sources_sha256" in data:
                sources[path.name]["executed_local_sources_sha256"] = data[
                    "executed_local_sources_sha256"
                ]
            lines.extend(
                [
                    "",
                    f"[{variant}]",
                    f"budget = {budget}",
                    f"strict_curve_through = {data['checkpoints'][-1]['iteration'] if game == 'kuhn' else 50}",
                ]
            )
            if target is not None:
                lines.append(f"target_nash_conv = {target!r}")
            for point in data["checkpoints"]:
                lines.extend(["", f"[[{variant}.checkpoints]]"])
                lines.extend(f"{key} = {value!r}" for key, value in point.items())
        output = HERE.parents[1] / "fixtures" / f"{game}.toml"
        output.parent.mkdir(exist_ok=True)
        output.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    provenance = {
        "open_spiel_version": "2.0.2",
        "reproducer_script_sha256": hashlib.sha256(
            (HERE / "capture.py").read_bytes()
        ).hexdigest(),
        "reproducer_dcfr_reference_sha256": dcfr_source_sha256(),
        "requirements_sha256": hashlib.sha256(
            (HERE / "requirements.txt").read_bytes()
        ).hexdigest(),
        "captures": sources,
        "script_provenance_note": "Reproducer hashes identify the current capture script and its shared DCFR module, not the exact bytes executed by historical captures. Original captures predate extraction of the module and retain their original hashes. New captures record their executed local sources separately. Native CFR/Plus update calls are unchanged.",
        "distribution": {
            "registry": "https://pypi.org/project/open-spiel/2.0.2/",
            "platform": platform.platform(),
            "installed_wheel_tags": [
                line.removeprefix("Tag: ")
                for line in importlib.metadata.distribution("open-spiel")
                .read_text("WHEEL")
                .splitlines()
                if line.startswith("Tag: ")
            ],
            "installed_version": importlib.metadata.version("open-spiel"),
            "installed_pyspiel_binary_sha256": hashlib.sha256(
                Path(pyspiel.__file__).read_bytes()
            ).hexdigest(),
            "license": "Apache-2.0",
            "license_source": "https://github.com/google-deepmind/open_spiel/blob/v2.0.2/LICENSE",
        },
        "reference_source": "https://github.com/google-deepmind/open_spiel/tree/v2.0.2",
        "uniform_constants_source": "https://github.com/google-deepmind/open_spiel/blob/v2.0.2/open_spiel/python/algorithms/exploitability_test.py",
        "variant_scope": {
            "cfr": "unmodified OpenSpiel Python CFRSolver",
            "cfr_plus": "unmodified OpenSpiel Python CFRPlusSolver, linear averaging",
            "dcfr": "OpenSpiel Python scalar CFRSolver plus this project's documented discount extension; not an upstream DCFR implementation",
        },
        "tolerance": {"absolute": 1e-9, "relative": 1e-6},
        "checkpoint_policy": "All 80 captured checkpoints remain exported and recorded. All Kuhn checkpoints retain the original strict comparison. Leduc uses the same strict prefix through iteration 50 for every variant; later trajectory differences are diagnostic. Independent actual-policy metrics and shared-state replay are enforced separately by verify_snapshots.py.",
        "reviewed_acceptance": {
            "evidence": "diagnostics/ contains OpenSpiel-only counterfactual-scale and reversed-chance controls demonstrating accumulated trajectory sensitivity. Astra's shared-state audit agreed to roundoff on all 18 replay pairs and independently checked actual Rust policy metrics before accepting this change.",
            "replay_accumulators": {"absolute": 1e-12, "relative": 1e-12},
            "replay_current_policy_absolute": 1e-12,
            "independent_metrics_absolute": 1e-12,
            "leduc_vanilla_final_nash_conv": 0.005,
        },
        "budget_selection": "Budgets follow measured captures. Kuhn, CFR+ and DCFR absolute gates are retained; the reviewed Leduc vanilla final bound is added. No captured checkpoint is removed.",
    }
    (HERE / "provenance.json").write_text(
        json.dumps(provenance, indent=2) + "\n", encoding="utf-8", newline="\n"
    )


if __name__ == "__main__":
    main()
