"""Export Rust-test TOML only from completed, inspected reference captures."""

import hashlib
import importlib.metadata
import json
from pathlib import Path

import pyspiel

HERE = Path(__file__).parent
BUDGETS = {
    "kuhn": {"cfr": (10000, 1e-3), "cfr_plus": (200000, 1e-5), "dcfr": (200000, 1e-5)},
    "leduc": {"cfr": (10000, None), "cfr_plus": (1000, 1e-3), "dcfr": (2000, 1e-4)},
}


def main():
    """Refuse missing budgets, incomplete runs, or residuals outside their gate."""
    sources = {}
    for game, variants in BUDGETS.items():
        lines = ["# Generated by tests/reference/openspiel/export_fixtures.py."]
        for variant, (budget, target) in variants.items():
            path = HERE / f"{game}_{variant}.json"
            data = json.loads(path.read_text(encoding="utf-8"))
            if not data["complete"]:
                raise ValueError(f"Incomplete capture: {path.name}")
            measured = next(p for p in data["checkpoints"] if p["iteration"] == budget)
            if target is not None and measured["nash_conv"] >= target:
                raise ValueError(
                    f"Captured {game}/{variant} misses its fixed accuracy gate"
                )
            sources[path.name] = {
                "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
                "command": f"python tests/reference/openspiel/capture.py --game {game} --variant {variant} --max-iterations {data['checkpoints'][-1]['iteration']}",
                "game_parameters": data["game_parameters"],
                "captured_utc": data["captured_utc"],
                "executed_upstream_cfr_python_sha256": data["cfr_python_sha256"],
            }
            lines.extend(
                [
                    "",
                    f"[{variant}]",
                    f"budget = {budget}",
                ]
            )
            if target is not None:
                lines.append(f"target_nash_conv = {target!r}")
            for point in data["checkpoints"]:
                if point["iteration"] > 10000:
                    continue
                lines.extend(["", f"[[{variant}.checkpoints]]"])
                lines.extend(f"{key} = {value!r}" for key, value in point.items())
        output = HERE.parents[1] / "fixtures" / f"{game}.toml"
        output.parent.mkdir(exist_ok=True)
        output.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    provenance = {
        "open_spiel_version": "2.0.2",
        "reproducer_script_sha256": hashlib.sha256(
            (HERE / "capture.py").read_bytes()
        ).hexdigest(),
        "requirements_sha256": hashlib.sha256(
            (HERE / "requirements.txt").read_bytes()
        ).hexdigest(),
        "captures": sources,
        "script_provenance_note": "The capture script gained a separately labeled DCFR option and was formatted while earlier Python processes were running. This hash identifies the final reproducer, not the exact bytes executed by every capture. Native CFR/Plus update calls were unchanged. Each capture separately hashes its executed upstream cfr.py.",
        "distribution": {
            "registry": "https://pypi.org/project/open-spiel/2.0.2/",
            "wheel": "open_spiel-2.0.2-cp312-cp312-win_amd64.whl",
            "installed_version": importlib.metadata.version("open-spiel"),
            "installed_pyspiel_binary_sha256": hashlib.sha256(
                Path(pyspiel.__file__).read_bytes()
            ).hexdigest(),
            "license": "Apache-2.0",
            "license_source": "https://github.com/google-deepmind/open_spiel/blob/v2.0.2/LICENSE",
        },
        "reference_source": "https://github.com/google-deepmind/open_spiel/tree/v2.0.2",
        "uniform_constants_source": "https://github.com/google-deepmind/open_spiel/blob/v2.0.2/open_spiel/python/algorithms/exploitability_test.py",
        "variant_scope": {
            "cfr": "unmodified OpenSpiel Python CFRSolver",
            "cfr_plus": "unmodified OpenSpiel Python CFRPlusSolver, linear averaging",
            "dcfr": "OpenSpiel Python scalar CFRSolver plus this project's documented discount extension; not an upstream DCFR implementation",
        },
        "tolerance": {"absolute": 1e-9, "relative": 1e-6},
        "budget_selection": "captured residual must meet the pre-existing absolute gate; no reference checkpoint is removed",
    }
    (HERE / "provenance.json").write_text(
        json.dumps(provenance, indent=2) + "\n", encoding="utf-8", newline="\n"
    )


if __name__ == "__main__":
    main()
