"""
Generates the design token block for this site.

Two things live here that cannot be written accurately by hand:

  1. The palette in oklch, converted properly from the signed-off sRGB hexes
     rather than eyeballed.
  2. The WCAG contrast report, measured against the surface each colour is
     actually used on, so a "muted" tone cannot quietly ship below 4.5:1.

Run it after changing any hex in PALETTE:

    python tools/gen_tokens.py            # print the block and the report
    python tools/gen_tokens.py --write    # rewrite the block in css/styles.css
    python tools/gen_tokens.py --check    # exit 1 if the CSS has drifted

The block in css/styles.css between the GENERATED markers is this script's
output. Do not hand-edit inside the markers.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

CSS = Path(__file__).resolve().parent.parent / "css" / "styles.css"
START = "/* ==== GENERATED by tools/gen_tokens.py. Do not hand-edit. ==== */"
END = "/* ==== END GENERATED ==== */"

# Carried over from website-v2 unchanged, because it is already measured and
# because every demo ships in the v2 format. The orange reads as trade safety
# hi-vis rather than as R&R's own mark.
#
# When the client gives us brand colours, change the hexes below and run
#     python tools/gen_tokens.py --write
# That is the whole job. Nothing else in the CSS names a colour.
PALETTE: list[tuple[str, str, str]] = [
    # token,          hex,        note
    ("walnut",        "#100904", "page canvas, the void behind every reveal"),
    ("walnut-deep",   "#080402", "the hero panel, one step below the canvas"),
    ("bark",          "#382416", "elevated surface, the only chromatic step up"),
    ("bark-lifted",   "#48301e", "bark, hovered"),
    ("cork",          "#40372e", "decorative rules only, never the sole carrier of meaning"),
    ("driftwood",     "#6c5f51", "structural divider on the canvas. Never text: it is 3.2:1"),
    ("cream",         "#ffedd7", "primary text, the system's signature warmth"),
    ("cream-dim",     "#c8b8a4", "secondary text on the canvas"),
    ("sand",          "#8a7c6d", "muted text, and the structural divider on a bark panel"),
    ("ember",         "#dc5000", "editorial accent: credits, tags, short emphasis"),
    ("ember-bright",  "#ff6a1f", "the CTA fill, and the tap to call button"),
    ("ember-hover",   "#ff7c3a", "CTA, lifted"),
    ("ember-ink",     "#160f07", "text on an ember surface"),
    ("ember-ink-2",   "#352516", "secondary text on an ember surface"),
]

# Every pair we actually rely on: (foreground, background, minimum, what it is).
CONTRAST_PAIRS: list[tuple[str, str, float, str]] = [
    ("cream",        "walnut",       4.5, "body text on the canvas"),
    ("cream",        "walnut-deep",  4.5, "headlines in the hero"),
    ("cream",        "bark",         4.5, "text on the elevated surface"),
    ("cream-dim",    "walnut",       4.5, "secondary text on the canvas"),
    ("sand",         "walnut",       4.5, "muted text on the canvas"),
    ("ember",        "walnut",       4.5, "accent text on the canvas"),
    ("ember-bright", "walnut",       4.5, "CTA border and label on the canvas"),
    ("ember-ink",    "ember-bright", 4.5, "text on the CTA"),
    ("ember-ink-2",  "ember-bright", 4.5, "secondary text on the CTA"),
    ("driftwood",    "walnut",       3.0, "structural divider on the canvas"),
    ("sand",         "bark",         3.0, "structural divider on an elevated panel"),
]

# Measured and printed, but NOT asserted. WCAG 1.4.11 governs UI components and
# state indicators; it does not govern decoration. ORYZO's cork hairline is
# deliberately near-invisible and that is the look. It is allowed to stay below
# 3:1 on one condition, which the build has to keep honouring: it is never the
# only thing telling you something. Every section it separates is also separated
# by whitespace and a heading, and no state is signalled by it alone. Anything
# that has to be seen uses driftwood.
DECORATIVE_PAIRS: list[tuple[str, str, str]] = [
    ("cork", "walnut", "dashed rule on the canvas"),
    ("cork", "bark",   "edge on an elevated panel"),
]


def srgb(hex_colour: str) -> tuple[float, float, float]:
    h = hex_colour.lstrip("#")
    return tuple(int(h[i : i + 2], 16) / 255 for i in (0, 2, 4))  # type: ignore[return-value]


def linearise(c: float) -> float:
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def luminance(hex_colour: str) -> float:
    r, g, b = (linearise(c) for c in srgb(hex_colour))
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def contrast(fg: str, bg: str) -> float:
    a, b = luminance(fg), luminance(bg)
    lo, hi = sorted((a, b))
    return (hi + 0.05) / (lo + 0.05)


def to_oklch(hex_colour: str) -> tuple[float, float, float]:
    """sRGB -> linear -> LMS -> Oklab -> Oklch. Bjorn Ottosson's matrices."""
    r, g, b = (linearise(c) for c in srgb(hex_colour))

    l = 0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b
    m = 0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b
    s = 0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b

    l_, m_, s_ = (v ** (1 / 3) if v >= 0 else -((-v) ** (1 / 3)) for v in (l, m, s))

    L = 0.2104542553 * l_ + 0.7936177850 * m_ - 0.0040720468 * s_
    a = 1.9779984951 * l_ - 2.4285922050 * m_ + 0.4505937099 * s_
    bb = 0.0259040371 * l_ + 0.7827717662 * m_ - 0.8086757660 * s_

    import math

    C = math.hypot(a, bb)
    H = math.degrees(math.atan2(bb, a)) % 360
    return L * 100, C, H


def block() -> str:
    lines = [START, ":root {", "  /* Palette. Generated from the signed-off sRGB values, not re-picked. */"]
    width = max(len(t) for t, _, _ in PALETTE)
    for token, hex_colour, note in PALETTE:
        L, C, H = to_oklch(hex_colour)
        value = f"oklch({L:.1f}% {C:.3f} {H:.1f})"
        pad = " " * (width - len(token))
        lines.append(f"  --{token}:{pad} {value}; /* {hex_colour} {note} */")
    lines.append("}")
    lines.append(END)
    return "\n".join(lines)


def report() -> tuple[str, bool]:
    out, ok = [], True
    out.append("Contrast, measured against the surface each colour actually sits on:")
    for fg, bg, minimum, what in CONTRAST_PAIRS:
        fg_hex = next(h for t, h, _ in PALETTE if t == fg)
        bg_hex = next(h for t, h, _ in PALETTE if t == bg)
        ratio = contrast(fg_hex, bg_hex)
        passed = ratio >= minimum
        ok = ok and passed
        mark = "PASS" if passed else "FAIL"
        out.append(f"  [{mark}] {ratio:5.2f}:1  (min {minimum})  {fg} on {bg}  - {what}")
    return "\n".join(out), ok


def splice(css_text: str, new_block: str) -> str:
    pattern = re.compile(re.escape(START) + r".*?" + re.escape(END), re.DOTALL)
    if not pattern.search(css_text):
        raise SystemExit("Could not find the GENERATED markers in css/styles.css.")
    return pattern.sub(lambda _: new_block, css_text)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="rewrite the block in css/styles.css")
    parser.add_argument("--check", action="store_true", help="exit 1 if the CSS has drifted")
    args = parser.parse_args()

    new_block = block()
    text, ok = report()

    if args.check:
        if not CSS.exists():
            print("css/styles.css does not exist yet.", file=sys.stderr)
            return 1
        current = CSS.read_text(encoding="utf-8")
        match = re.search(re.escape(START) + r".*?" + re.escape(END), current, re.DOTALL)
        if match is None:
            print("css/styles.css has no GENERATED block.", file=sys.stderr)
            return 1
        if match.group(0) != new_block:
            print("css/styles.css has drifted from tools/gen_tokens.py.", file=sys.stderr)
            print("Run: python tools/gen_tokens.py --write", file=sys.stderr)
            return 1
        if not ok:
            print(text, file=sys.stderr)
            return 1
        print("Tokens in sync, contrast passes.")
        return 0

    if args.write:
        CSS.write_text(splice(CSS.read_text(encoding="utf-8"), new_block), encoding="utf-8")
        print(f"Wrote the token block into {CSS}.")
    else:
        print(new_block)

    print()
    print(text)
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
